/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;
import observerTemperatura.*;

/**
 *
 * @author M
 */
public class Janela extends javax.swing.JFrame {

    CentralDosDados dadosTemperaturaDasCidades = new CentralDosDados();
    TemperaturaDeBrasilia brasilia = new TemperaturaDeBrasilia(dadosTemperaturaDasCidades);
    TemperaturaDeCampoGrande campoGrande = new TemperaturaDeCampoGrande(dadosTemperaturaDasCidades);
    TemperaturaDeCuiaba cuiaba = new TemperaturaDeCuiaba(dadosTemperaturaDasCidades);
    TemperaturaDeGoiania goiania = new TemperaturaDeGoiania(dadosTemperaturaDasCidades);
    
    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAtualizar = new javax.swing.JButton();
        jTextFieldCampoGrande = new javax.swing.JTextField();
        jTextFieldCuiaba = new javax.swing.JTextField();
        jTextFieldBrasilia = new javax.swing.JTextField();
        jTextFieldGoiania = new javax.swing.JTextField();
        jLabelTemperaturaDasCidades = new javax.swing.JLabel();
        jLabelBrasilia = new javax.swing.JLabel();
        jLabelCampoGrande = new javax.swing.JLabel();
        jLabelCuiaba = new javax.swing.JLabel();
        jLabelGoiania = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEMPERATURAS DAS CAPITAIS");
        setBackground(new java.awt.Color(255, 255, 255));

        jButtonAtualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAtualizar.setForeground(new java.awt.Color(204, 0, 51));
        jButtonAtualizar.setText("ATUALIZAR");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jLabelTemperaturaDasCidades.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTemperaturaDasCidades.setForeground(new java.awt.Color(102, 102, 255));
        jLabelTemperaturaDasCidades.setText("TEMPERATURAS DAS CAPITAIS DO CENTRO OESTE");

        jLabelBrasilia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBrasilia.setText("BRASILIA");

        jLabelCampoGrande.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCampoGrande.setText("CAMPO GRANDE");

        jLabelCuiaba.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCuiaba.setText("CUIABÁ");

        jLabelGoiania.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelGoiania.setText("GOIÂNIA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTemperaturaDasCidades)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelBrasilia)
                                        .addGap(52, 52, 52))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCampoGrande)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelCuiaba)
                                    .addGap(63, 63, 63)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelGoiania)
                                .addGap(57, 57, 57)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldGoiania, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jTextFieldCuiaba, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jTextFieldCampoGrande)
                            .addComponent(jTextFieldBrasilia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAtualizar)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelTemperaturaDasCidades)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBrasilia)
                    .addComponent(jTextFieldBrasilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtualizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCampoGrande)
                    .addComponent(jTextFieldCampoGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCuiaba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCuiaba))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGoiania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGoiania))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        int brasilia = Integer.parseInt(jTextFieldBrasilia.getText());
        int campoGrande = Integer.parseInt(jTextFieldCampoGrande.getText());
        int cuiaba = Integer.parseInt(jTextFieldCuiaba.getText());
        int goiania = Integer.parseInt(jTextFieldGoiania.getText());
        DadosDaTemperaturaDasCidades dados = new DadosDaTemperaturaDasCidades(brasilia, campoGrande, cuiaba, goiania);
        dadosTemperaturaDasCidades.setDados(dados);
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JLabel jLabelBrasilia;
    private javax.swing.JLabel jLabelCampoGrande;
    private javax.swing.JLabel jLabelCuiaba;
    private javax.swing.JLabel jLabelGoiania;
    private javax.swing.JLabel jLabelTemperaturaDasCidades;
    private javax.swing.JTextField jTextFieldBrasilia;
    private javax.swing.JTextField jTextFieldCampoGrande;
    private javax.swing.JTextField jTextFieldCuiaba;
    private javax.swing.JTextField jTextFieldGoiania;
    // End of variables declaration//GEN-END:variables
}
